apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
spec:
  selector:
    app: simple-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
