apiVersion: v1
kind: Service
metadata:
  name: svc-httpd
spec:
  selector:
    app: simple-httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
  type: NodePort
